project_id = "murdekixacjoescjsmmk"

[functions.discord-bot]
verify_jwt = false

[functions.monday-file-upload]
verify_jwt = false

[functions.monday-webhook]
verify_jwt = false

[functions.monday-webhook-sync]
verify_jwt = false
